### ISSUE TITLE
custom.mk: add variables for compiler-specific flags

### ISSUE THREAD

**Issue by mikebentley15** [PRUNERS/FLiT#125]
There may be instances where you want a flag to be used with "g++" and not with "clang++" or vica-versa.  For example, compiler warning flags that may be defined in one but not the other.

I'm thinking variables such as:

- `GCC_REQUIRED`
- `CLANG_REQUIRED`
- `ICPC_REQUIRED`
- `GCC_LD`
- `CLANG_LD`
- `ICPC_LD`

or something like that.  Of course, this makes things more difficult when I go to implement and fix issue #120.  Do I want a custom variable for each compiler version?  Are these specified in the toml file or in `custom.mk`?  Maybe it should be put into `flit-config.toml` in that case.

**Comment by jjgarzella** [comment]
As part of the support for FORTRAN and the support necessary to test Physics Libraries, I'm going to implement this issue in my fortran branch. 

I am definitely in favor of these being in flit-config.toml. As compiler names are now generated by the script, it would require custom.mk users to know exactly what the script will output. If we change the way the script transforms names, that would break things. Overall, putting it in the toml is the best way to go, in my opinion.

**Comment by mikebentley15** [comment]
Thank you, JJ.  Let me know if you want help implementing these features or if you want to have another architecture and design meeting.
