### ISSUE TITLE
Bisect to order findings by magnitude of variability

### ISSUE THREAD

**Issue by mikebentley15** [PRUNERS/FLiT#172]
Not all variability is equal.  Yes, bisect's goal is to find all functions that show variability.  However, as a developer looking to find and fix these reproducibility bugs, I will likely want to work on the most influential one(s) and ignore those that only cause minor variations.

It would be extremely helpful to sort the findings by how much variability the file(s)/function(s) cause when optimized.  There are two approaches for getting such a number:

1. Compile everything except the one file/function under ground-truth and capture the comparison value -- how much it contributes by itself
2. Compile everything except the one file/function under the full optimization, capture the comparison value, and subtract it from the full optimization comparison value -- how much the comparison value changes when it is removed, may actually be to make it bigger/worse, signifying cancellation of error terms.

It is unclear which approach is better in identifying the contribution of variability.

**Comment by mikebentley15** [comment]
It seems that the first approach seems easier to understand.  It is likely that the two approaches would have similar results, so for ease of understanding and implementation, I opt to do the first suggestion.

**Comment by mikebentley15** [comment]
So it is easy to specify that I want the major contributors in the file bisect, but since I have implemented #173, the symbol bisect is done one once for each file.

I have a few questions:

1. How do I ascertain the biggest k contributing functions?
2. Do I simply say that this implementation will do the biggest k _source file contributors_?  But will find all function contributors in each file?
3. Or do I find the biggest k _source file contributors_ and then the biggest k _symbol contributors_ for each file?  This would be easy.
4. I could combine the symbols for all of the found source files and have that be my search space.  But I worry that it would cause the complexity to go back up.  Is this okay?

I like options 3 and 4.  3 is the easiest to implement and makes sense, I would just document in the help documentation that it is the expected behavior.  Number 4 probably makes more sense since the person probably only cares about the top k functions.  If they set k to 2, they wouldn't want the top 2 functions from each of the 2 identified files, but that wouldn't be a big deal either.

Option 3:

- Pro: easiest to implement
- Pro: can identify when -fPIC destroys any possibility of identifying functions
- Con: may return more functions than the user wanted or expected
- Con: may take longer than option 4, depending

Option 4:

- Pro: more intuitive
- Pro: may be faster than option 3, depending
- Con: cannot identify when -fPIC destroys the possibility of identifying functions
- Con: may give confusing results, saying file 1 is the biggest contributor, but finding no function from within that file (because of -fPIC)
- Con: can run into the search space explosion problem described in #173 

After weighing the pros and cons, I choose to go with option 3.  Primarily because of being able to identify when -fPIC destroys optimizations.  True I could check this separately, but that makes the logic unnecessarily complex I think.  Also, it's not too far of a stretch to say give me the biggest k offenders from each of the k biggest offending files.

**Comment by ganeshutah** [comment]
Option 3 sounds great. But for our paper, we can say that both these
options are good to provide. If we can provide one example where option 4
helps the user more, that would strengthen the paper.

Ganesh

**Comment by mikebentley15** [comment]
Fixed by pull request #197
