### ISSUE TITLE
Reimplement continuous integration

### ISSUE THREAD

**Issue by mikebentley15** [PRUNERS/FLiT#182]
At one point, we had Travis CI working for FLiT.  But that has gone into disarray and disabled.  We would like to have automated tests run for every pull request and the build performed for every push at the very least.  This should hopefully find bugs early.  This is especially important since there was recently a pull request that was pulled in that broke some functionality.  Since then, an automated test has been added that found the problem.

**Comment by IanBriggs** [comment]
closed with #185
