### ISSUE TITLE
FLiT fails to work with GCC 4 or GCC 5

### ISSUE THREAD

**Issue by mikebentley15** [PRUNERS/FLiT#183]
This is because of the linker flag `-no-pie`.  This linker flag was added in GCC 6 because of a configuration option to default to linking position independent executables.  This `-no-pie` option was also added to turn off this default behavior for a particular build.  But before GCC 6, this option was not there and not needed.

This should be fixed because we want to be able to support older versions of compilers.  Our ideal requirement is that we support any compiler that supports C++ 11.

**Comment by IanBriggs** [comment]
Closed with #185
