### ISSUE TITLE
Emojis in issue template do not work on GitHub anymore

### ISSUE THREAD

**Issue by mikebentley15** [PRUNERS/FLiT#228]
## Bug Report

**Describe the problem**
The issue templates have emojis in them, but they are not being rendered properly.

**Suggested Fix**
Remove the emojis.

**Alternative approaches:**
Research the problem if others are seeing the same thing.  Issue a bug report to GitHub if necessary.

**Comment by IanBriggs** [comment]
Unable to reproduce.

Using Chrome Version 69.0.3497.100 on Mac OS Version 10.13.6.

![flit_emoji](https://user-images.githubusercontent.com/2159992/46820117-a257d180-cd42-11e8-8894-8a93de498746.png)

**Comment by mikebentley15** [comment]
Looks like this is a problem with my browser, not with GitHub.  It seems many other people have this issue with Google Chrome.  Oh well, not a big deal.
