### ISSUE TITLE
Linker flag `-no-pie` not supported in older versions of clang

### ISSUE THREAD

**Issue by jjgarzella** [PRUNERS/FLiT#239]
## Bug Report

**Describe the problem**
Older versions of clang (such as clang 3.8) do not have the flang `-no-pie`, but instead use `-nopie`. In modern versions they are aliased.

**Suggested Fix**
There is already a switch which disables this flag if we are using an older version of gcc. Simply adding another switch which checks if the compiler is clang would do.

**Comment by mikebentley15** [comment]
Thank you JJ for this bug report.  Do you know in which version of Clang, the flag was changed?  Or should we simply use `-nopie` for Clang all the time?  I'm thinking the latter.

**Comment by jjgarzella** [comment]
I'm also thinking the latter. I believe it was fixed in 2017, which would mean LLVM 4 or 5
