### ISSUE TITLE
Flit bisect does not know which compiler it was given

### ISSUE THREAD

**Issue by IanBriggs** [PRUNERS/FLiT#255]
## Bug Report

**Describe the problem**
We have required flags for each compiler, notably the --gcc-toolchain for clang and -g++-name for intel. When running bisect these are not used.

**Suggested Fix**
A flag can be added to bisect which specifies the type of compiler.
In the absence of the flag the compiler used can be matched against the ones in the flit_config.
Failing that we can fall back to assuming that the user has ensured the compiler is set up.

Workaround: When running bisect specify the required flags at the end of the compile string.

**Alternative approaches:**
Run the compiler with --version and search the output for known names.

**Comment by mikebentley15** [comment]
Additional workaround information:

For Clang, give the additional flag `--gcc-toolchain=<path to gcc folder>`.  For example, if GCC is installed in `~/compilers/gcc-8.2.0-install`, and you want to perform bisect with `clang++ -O3 -funsafe-math-optimizations` with double precision and test case `flit-test-case`, then you would do the following:

```{bash}
$ flit bisect --precision=double "clang++ -O3 -funsafe-math-optimizations --gcc-toolchain=<path to gcc folder>" flit-test-case
```

The proposed fix would add a new flag to `flit bisect`.  For example, `--compiler-type=clang` as an additional argument.  Giving this argument would automatically have FLiT generate the `--gcc-toolchain` flag for you.
