### ISSUE TITLE
Problem with DB creation

### ISSUE THREAD

**Issue by Geof23** [PRUNERS/FLiT#37]
IF the FLiT DB already exists on a machine, and a postgres function changes (between what's installed and what's in the dump that we're restoring), the function does NOT get updated.

We can look at the fine grained operations in the .sql dump file, and otherwise find options to replace all functions . . .?  A quick, easy solution would be to rename the existing 'FLiT' database, but that would get messy

**Comment by mikebentley15** [comment]
Since postgres is no longer a supported database, this bug is no longer relevant.
