### ISSUE TITLE
Return arbitrary length score array

### ISSUE THREAD

**Issue by mikebentley15** [PRUNERS/FLiT#49]
There are many FP algorithms that generate more than one FP result.  Consider for example the QR decomposition of a matrix.  That algorithm returns basically two matrices the same size as the input matrix.  It may be difficult, if not impossible, to come up with a way to shrink the two output matrices into a single FP value to be returned.  Ideally, we would want to return the two matrices for later comparison against different compilations of the same run.

Right now, you can return two different values from any test.  Why two? Why not simply return a vector?  That way you can return one, two, or many.  For the example above, the test author could flatten the two matrices into a single vector to use as a comparison for later.

The biggest challenge here is how to deal with this in the database.

**Comment by ganeshutah** [comment]
To answer these questions concerning FLiT, it has to be kept in mind that
we are aiming for a tool that serves some users in some well-specified
circumstances. Going beyond that (all users, serve in all circumstances)
will not be wise. As the saying goes "those who try to please all, please
none."

It is good to limit usage to very narrowly specified but important areas of
HPC where there are actual problems waiting to be addressed.

To address the three emails I saw so far quickly:

1. Zero inputs supported - seems fine

2. Time measurement : robust time measurements that compare the same kinds
of timers on a given platform (for a given routine) seems fine. Collecting
some basic info on runtime, as a default, seems fine.  Whatever be the
decision -- make sure that the primary user community (and their important
use-cases) would be OK with it.   It is perhaps not reasonable (in the
short term) to hope for more than 2-3 users and 3-4 important use-cases for
each user. But at least, having this much citable evidence seems important.

So to have a user community and actually named use-cases to justify such
decisions would be reassuring.

3. Vector of outputs : what is the stopping point? How about entire coupled
ocean / atmosphere simulation data? That will be HUGE, and is already in
the space of "unreasonable".

 So having floats or simple 1D vectors of upto say 128 words seems fine.

 Anything beyond : insist that the onus is on the end-user to summarize
their data into these output formats by providing us an abstraction
function (say that is always -O0 compiled, so the abstraction function is a
stable object).

Thus they can condense the entire ocean simulation data by recording the
min, max, median, mean, and some norms.  The FLiT tool itself that way does
not have to then be able to compare one ocean simulation against another.

128 words is an arbitrary decision ... but it looks like many problems can
have a meaningful  'score' expressible in 128 double-precision words (pick
your favorite number!).

 Confirm this is the case for the popular users / use-cases, then stick
with it.

Ganesh

**Comment by mikebentley15** [comment]
Thanks Ganesh for your input.  It has been feedback from potential users
here to be able to return an entire simulation since the comparison is done
later.  I'm wrestling with this as well.  Maybe this feature doesn't get
done and we instead hard code golden answers.  Maybe the test generates the
output into a file with a custom comparator.  Maybe we redesign FLiT so
that comparisons are done at runtime rather than after.  Maybe we need to
come up with sufficient statistics for each use case.

I agree with what you said.  I will carefully think about these options to
see which one will be the cleanest and easiest to implement and maintain.

Thanks,
Mike

**Comment by ganeshutah** [comment]
In my experience, floating-point  often gives an excuse to be ultra-lazy.
People operate on numbers worry-free, not even knowing what binade their
numbers are riding in (what exp values?). I think a value-profile of every
application can be illuminating. It may allow us to identify modules that
are riding in the highest of binades. Even this feedback is first step
IMHO. W/o knowing this, every solution is "looking under the light" or
putting a bandaid wherever the body-part is most accessible.

If a value-profile reveals surprises (M1,M2 are riding in the high ULP
binades, M3,M4... are in very low binades), at least one can stop looking
at M3,M4

Richard Hamming wrote a paper even as early as 1970s speculating about the
probability of seeing particular FP values! A few follow-ups exist too.
This shows that scientists did think about values then. Hamming does some
heavy-duty math that is undoubtedly elegant but I suspect not scalable -
but today,  we can simply measure --- say using Dyninst-based profiling.

These are my 3 cents (3 > 2 ) :-)

Ganesh
